#!/bin/sh
echo 0 >/proc/sys/kernel/tdlsm/lsm_enable
#chmod 0777 /mnt/sata/0/
mkdir /dvr/z_test/dvr/
mount -t nfs -o intr,nolock,rsize=1024,wsize=1024 10.30.30.183:/home/newer/yangweiyu/dvr/ /dvr/z_test/ 